services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    ports:
      - "8080:8080"
    volumes:
      - ./gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]
    restart: unless-stopped
