services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    volumes:
      - gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]
    restart: unless-stopped

volumes:
  gmapsdata:
