services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    restart: unless-stopped
    command:
      - "-data-folder"
      - "/gmapsdata"
      - "-concurrency"
      - "2"
    volumes:
      - gmapsdata:/gmapsdata

volumes:
  gmapsdata:
