version: "3.8"

services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    container_name: gmaps-scraper
    ports:
      - "8080:8080"
    volumes:
      - ./gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]
