services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    restart: unless-stopped
    command: ["-web", "-addr", ":8080", "-c", "1", "-data-folder", "/gmapsdata"]
    volumes:
      - gmapsdata:/gmapsdata

volumes:
  gmapsdata:
