services:
  gmaps-scraper:
    image: gosom/google-maps-scraper
    restart: unless-stopped
    volumes:
      - gmapsdata:/gmapsdata
    command: ["-data-folder", "/gmapsdata"]

volumes:
  gmapsdata:
